name: Release

on:
  push:
    tags:
      - 'v*.*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: false

jobs:
  release:
    name: GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.tag || github.ref }}
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Move major version tag
        run: |
          MAJOR=$(echo ${{ inputs.tag || github.ref_name }} | sed 's/\(v[0-9]*\).*/\1/')
          git tag -f $MAJOR ${{ inputs.tag || github.ref_name }}
          git push origin $MAJOR --force

      - uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          draft: true
          tag_name: ${{ inputs.tag || github.ref_name }}
          token: ${{ secrets.GH_PAT }}
